# Generated by Django 4.1.5 on 2023-04-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='material',
        ),
        migrations.CreateModel(
            name='Order_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.order')),
            ],
        ),
    ]
