# Generated by Django 4.1.5 on 2023-04-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_remove_order_material_order_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
