# Generated by Django 4.1.7 on 2023-04-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_alter_order_email_alter_order_mobile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_materials',
            new_name='Order_material',
        ),
    ]
